name: ecdna-aa-workflow
channels:
  - r
  - free
  - main
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - qualimap==2.2.2d 
  - fastq-screen==0.15.2 
  - fastqc==0.11.9 
  - fastp
  - cutadapt==4.1
  - future==0.18.2
  - Cython==0.29.28
  - pysam==0.15.3
  - Flask==1.1.4
  - matplotlib==2.2.5
  - numpy==1.16.6
  - scipy==1.3.0
  - bcftools=1.10.2
  - bwa=0.7.17
  - samtools=1.10
